networks:
  backend:

volumes:
  db-data:
    driver: local

services:
  postgres:
    image: 'postgres:15.1-alpine'
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
